# windowrulev2 = idleinhibit fullscreen, fullscreen:1

# windowrule = float, org.kde.polkit-kde-authentication-agent-1
# windowrule = float, nm-connection-editor|blueman-manager
# windowrulev2 = float, pavucontrol
# windowrule = float, eog # Eye of gnome
# windowrule = float, rofi
# windowrule = float, gnome-system-monitor
# windowrule = float, yad